### ISSUE TITLE
Auto-bottle reset to Off when loading game

### ISSUE THREAD

**Issue by HeavenP886** [DoctorFeelGoodMD/OxygenNotIncluded-Mods#13]
Hello !

When I place a hauling point in the map, assign it a ressource & turn On auto-bottle, dupes will deliver to it, but they wont after game reload. I have to manually turn auto-bottle Off, put it back On after save loading and dupes will start to deliver again to it.

I've made you a screen-capture of the bug to make things as clear as possible: https://www.youtube.com/watch?v=O1EwuTf5QNc

Attached [Player.log](https://github.com/DoctorFeelGoodMD/OxygenNotIncluded-Mods/files/12575084/Player.log)
_( I can also provide the output of the mod "Debug Console // by @Ony" if needed)_

Thanks !

**Comment by DoctorFeelGoodMD** [comment]
Thanks for pointing out this issue.
Box did not properly load serialized data due to an obvious error in my code.

Let me know if it occurs again.
