### ISSUE TITLE
Mod "Move This Here" crashes after hotfix on Dec. 4

### ISSUE THREAD

**Issue by skystreet8** [DoctorFeelGoodMD/OxygenNotIncluded-Mods#18]
Hi, I'm encountering a crash in entering the game when loading the mod "Move This Here". The mod Debug Console gives the following message:
`[09:05:51.977] [1] [INFO] Loading mod content Animation [Move This Here:2667816955] (provides DLL, Animation)
  [DebugConnsole][1]: Patching JobManager.WorkerThread.Run
  [Exception]: MissingMethodException: Method not found: bool .JobManager.DoNextWorkItem()
(wrapper dynamic-method) JobManager+WorkerThread.JobManager+WorkerThread.Run_Patch1(JobManager/WorkerThread)
JobManager+WorkerThread.ThreadMain (System.Object data) (at <4e08f3a60ed4421b99a6798f854897c4>:0)
System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) (at <8ce0bd04a7a04b4b9395538239d3fdd8>:0)
System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <8ce0bd04a7a04b4b9395538239d3fdd8>:0)
System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <8ce0bd04a7a04b4b9395538239d3fdd8>:0)
System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) (at <8ce0bd04a7a04b4b9395538239d3fdd8>:0)
System.Threading.ThreadHelper.ThreadStart (System.Object obj) (at <8ce0bd04a7a04b4b9395538239d3fdd8>:0)
UnityEngine.<>c:<RegisterUECatcher>b__0_0(Object, UnhandledExceptionEventArgs)`
The crash would prevent me from entering the game and I got stucked at the Klei logo interface. Could this have somthing to do with the latest multithreading fixes in version 644960?

**Comment by DoctorFeelGoodMD** [comment]
Weird, it runs just fine for me on 644960. Is anyone else getting this error?

**Comment by skystreet8** [comment]
> Weird, it runs just fine for me on 644960. Is anyone else getting this error?

Sorry to bother, I found that the bug was caused by the mod Debug Console. Thanks for your reply. 

If anyone else has the bug, edit the mods.json file and delete the mod Debug Console from the list will work.
