### ISSUE TITLE
Do you mind people translating your mods via "Mod Translation"?

### ISSUE THREAD

**Issue by DDEle** [DoctorFeelGoodMD/OxygenNotIncluded-Mods#2]
Hi DoctorFeelGoodMD,

I'm the author of [Mod Translation](https://steamcommunity.com/sharedfiles/filedetails/?id=2692663069). Do you mind people adding translations of your mods in including this one with Mod Translation? You don't need to change anything in your code (though welcomed) and you are not expected to keep your mod stable.

Mod Translation is designed for modders and translators and helps mods to be international easily and timely. It worked by downloading translations from a Github repo and overriding game strings with them, which means your mods don't need to update and force everyone to restart their game for a new language to appear, and Steam failing to update is not an issue either. Similarly, it also makes the translator's life easier when adding or updating mod text in terms of updating translations accordingly.
(continuing)

You may have noticed that there are only a few or none of your users who have requested or contributed translations of your mods. IMHO, one of its reason is that not all developers are active and people often get very slow responses when they request or contribute translations. Mod Translation can help solve this problem as only one of the active admins of Mod Translation Repo is necessary to accept translations for all mods (maybe one for each language later for QC). Meanwhile, translators can browse Mod Translation's repo and get a list of mods waiting for translations without opening the steam workshop page for every mod.

Mod Translation only holds strings for translation. Therefore, it will never be able to steal your work as users must subscribe to the original mod (or install locally if you have made that possible). Both the mod itself and the repository that holds translations are with MIT license and are free for everyone to use and contribute. If you don't mind me adding support to your mods, you will be able to opt out at any time later.

**Comment by DoctorFeelGoodMD** [comment]
Sure - it looks like Mod Translation just overrides the English strings with translated ones, so I certainly don't have any issue with it. Best of luck with the translations.

**Comment by DDEle** [comment]
Thanks a lot!
