### ISSUE TITLE
Hauling point storage amount resets to default on game load

### ISSUE THREAD

**Issue by strudo76** [DoctorFeelGoodMD/OxygenNotIncluded-Mods#3]
Posted issue on Steam Workshop page.
Tested with only this mod and Mod Updater installed.
Method to replicate:
:: Start ONI with only this mod and Mod Updater activated
:: Start a new survival game using the Spaced Out start
:: Mine some material to give sandstone to test with
:: Place a hauling point
:: Set hailing point limit to a lower amount (eg 20kg)
:: Save game
:: Load game

If you mouse over the hauling point (don't click it!), it will show the default value of 20,000kg, and dupes will continue to load the hauling point with material in excess of the user specified limit (20kg). When you do actually click the hauling point to select it, the load limit will revert to the user set limit and dupes will stop delivering at that point. If the amount loaded has already exceeded the user specified limit, there is no way to remove the excess as stuff cannot be removed, and the excess doesn't automatically fall out.

**Comment by DoctorFeelGoodMD** [comment]
fixed, thank you for reporting!
