### ISSUE TITLE
Dupes stop storage task when selecting hauling point

### ISSUE THREAD

**Issue by strudo76** [DoctorFeelGoodMD/OxygenNotIncluded-Mods#4]
Posted issue on Steam Workshop page.
Tested with only this mod and Mod Updater installed.
Method to replicate:
:: Start ONI with only this mod and Mod Updater activated
:: Start a new survival game using the Spaced Out start
:: Mine some material to give sandstone to test with
:: Place a hauling point
:: Set the hauling point to accept sandstone
:: Click off the hauling point so it is not selected
:: Wait for a dupe to start carrying sandstone to the hauling point
:: Before the dupe arrives at the hauling point, click on the hauling point to select it

When you select the hauling the point, any dupes carrying material to the hauling point will drop the material, and then restart the task. This can often lead to material being dropped in random locations, and makes it impossible to see how much is left to deliver or which dupes are currently doing errands for the hauling point without interrupting the deliveries already in progress.

**Comment by DoctorFeelGoodMD** [comment]
fixed, thank you for reporting!
