### ISSUE TITLE
It's not work with the game update-496912 which called [Move This Here]

### ISSUE THREAD

**Issue by GouDeng123** [DoctorFeelGoodMD/OxygenNotIncluded-Mods#5]
[Move This Here] is a very good mod . But it doesn't work after the Game Update-469612. I hope you can update it .
I'm a chinese , I'm not good at English . So thanks .

**Comment by DoctorFeelGoodMD** [comment]
Fixed 2/26, thanks for report!

**Comment by GouDeng123** [comment]
> Fixed 2/26, thanks for report!

It's very nice ! Thank you !

**Comment by GouDeng123** [comment]
![QQ截图20220227001342](https://user-images.githubusercontent.com/100468971/155850497-9ffa84bd-2ec1-4be2-b84e-4d51fd4f3221.png)
Can you see the picture ? The problme is I still cann't use the Hauling Pionts in my archive . I don't know where the problem come from 。

**Comment by GouDeng123** [comment]
I can use it after useing the mod called [MOD UPDATE] Probably because my file was not updated correctly .Sorry to bother you .

**Comment by DoctorFeelGoodMD** [comment]
No worries! Glad it is working!
