### ISSUE TITLE
After the update it still doesn't work. 

### ISSUE THREAD

**Issue by windghoul** [DoctorFeelGoodMD/OxygenNotIncluded-Mods#6]
After the update it still doesn't work.

**Comment by windghoul** [comment]
![image](https://user-images.githubusercontent.com/16053291/155884390-41bfa851-cd94-4628-85bd-0ee4f0836e90.png)

**Comment by DoctorFeelGoodMD** [comment]
Were you able to get it working? Make sure the file is updated properly from Steam.

**Comment by windghoul** [comment]
Cancel the subscription and subscribe again to use it. It may be necessary to download the latest file . It's working now . thx
